### ISSUE TITLE
Convert YAML to JSON

### ISSUE THREAD

**Issue by oxr463** [sjmulder/json-yaml#1]
- [x] JSON -> YAML
- [x] YAML -> JSON

**Comment by sjmulder** [comment]
Although YAML->JSON has some minor problems (e.g. YAML can be cyclic), those can be accounted for and I'm open to that feature but I don't currently have any plans to implement it myself.

**Comment by sjmulder** [comment]
4f52f5fd

- [x] JSON -> YAML
- [x] YAML -> JSON
